// codegen - walks IR and emits a single main.cpp

// type -> c++ type
const TYPE_MAP = {
  string: 'std::string',
  int: 'int',
  double: 'double',
  bool: 'bool',
  void: 'void',
  auto: 'auto',
  json: 'nlohmann::json',
  bytes: 'std::vector<uint8_t>',
  'vector<string>': 'std::vector<std::string>',
  'vector<int>': 'std::vector<int>',
  http_response: 'std::string',
  file: 'std::ifstream',
};

function cppType(t) { return TYPE_MAP[t] || 'std::string'; }
function cppLiteral(v) {
  if (v === null || v === undefined) return '""';
  if (typeof v === 'number') return String(v);
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'string') {
    if (/^\d+$/.test(v)) return v;
    if (v === 'true' || v === 'false') return v;
    return JSON.stringify(v);
  }
  return JSON.stringify(v);
}

export function emitCpp(ir) {
  const out = [];
  out.push(`// generated by nlpc - do not edit`);
  out.push(`#include <iostream>`);
  out.push(`#include <string>`);
  out.push(`#include <vector>`);
  out.push(`#include <sstream>`);
  // optional headers
  const reqs = (ir.requirements || []).map(r => r.name.toLowerCase());
  if (reqs.some(r => /nlohmann|json/.test(r))) out.push(`#include <nlohmann/json.hpp>`);
  if (reqs.some(r => /httplib|cpr|cpp-httplib/.test(r))) out.push(`#include <httplib.h>`);
  if (reqs.some(r => /spdlog/.test(r))) out.push(`#include <spdlog/spdlog.h>`);
  if (reqs.some(r => /fmt/.test(r))) out.push(`#include <fmt/core.h>`);
  out.push('');
  // declarations (functions)
  for (const d of ir.declarations || []) {
    if (d.kind === 'function') {
      const params = (d.params || []).map(p => `${cppType(p.type)} ${p.name}`).join(', ');
      out.push(`${cppType(d.returns || 'void')} ${d.name}(${params}) {`);
      if (d.returns && d.returns !== 'void') {
        out.push(`    return ${d.body?.length ? cppLiteral(d.body[0]?.value || '') : '""'};`);
      }
      out.push(`}`);
      out.push('');
    } else if (d.kind === 'variable') {
      out.push(`${cppType(d.type || 'string')} ${d.name} = ${cppLiteral(d.value)};`);
    }
  }
  // main
  out.push(`int main() {`);
  out.push(`    std::ios::sync_with_stdio(false);`);
  out.push(`    std::cin.tie(nullptr);`);
  out.push('');
  // behaviors
  const startBeh = (ir.behaviors || []).find(b => b.trigger === 'start');
  const routeBehs = (ir.behaviors || []).filter(b => b.trigger === 'route');
  if (routeBehs.length && reqs.some(r => /httplib|cpp-httplib/.test(r))) {
    out.push(`    httplib::Server svr;`);
    for (const r of routeBehs) {
      const method = (r.method || 'GET').toLowerCase();
      const path = r.path || '/';
      out.push(`    svr.${method}("${path}", [](const httplib::Request& req, httplib::Response& res) {`);
      for (const s of r.body || []) {
        const ln = emitStmt(s, '        ');
        if (ln) out.push(ln);
      }
      out.push(`        res.set_content("ok", "text/plain");`);
      out.push(`    });`);
    }
    // PORT env var lets PaaS hosts (heroku, fly, railway) inject the bind port
    // without a code change. std::getenv returns nullptr when unset.
    out.push(`    const char* nlpc_port = std::getenv("PORT");`);
    out.push(`    int port = nlpc_port ? std::atoi(nlpc_port) : 8080;`);
    out.push(`    svr.listen("0.0.0.0", port);`);
  } else if (startBeh) {
    for (const s of startBeh.body || []) {
      const ln = emitStmt(s, '    ');
      if (ln) out.push(ln);
    }
  }
  out.push(`    return 0;`);
  out.push(`}`);
  return out.join('\n');
}

function emitStmt(s, indent) {
  if (!s || !s.kind) return null;
  switch (s.kind) {
    case 'print': {
      const text = s.text || '';
      // always use std::cout to avoid fmt v12 ABI issues; fmt can still be linked if user adds it later
      return `${indent}std::cout << ${JSON.stringify(text)} << std::endl;`;
    }
    case 'ask': {
      const name = s.name || 'input';
      return [
        `${indent}std::cout << ${JSON.stringify(s.text || '> ')} << std::flush;`,
        `${indent}std::string ${name};`,
        `${indent}std::getline(std::cin, ${name});`,
      ].join('\n');
    }
    case 'set': {
      return `${indent}auto ${s.name} = ${cppLiteral(s.value)};`;
    }
    case 'call': {
      const args = (s.args || []).map(a => cppLiteral(a)).join(', ');
      return `${indent}${s.target}(${args});`;
    }
    case 'return': {
      return `${indent}return ${cppLiteral(s.value)};`;
    }
    case 'http_get': {
      const path = s.path || '';
      return [
        `${indent}auto cli = httplib::Client("http://localhost", 8080);`,
        `${indent}auto res = cli.Get("${path}");`,
        `${indent}if (res) std::cout << res->body << std::endl;`,
      ].join('\n');
    }
    case 'http_serve': {
      const port = s.port || '8080';
      return `${indent}svr.listen("0.0.0.0", ${port});`;
    }
    case 'http_route': {
      return `${indent}svr.get("${s.path || '/'}", [](const auto& req, auto& res) { res.set_content("ok", "text/plain"); });`;
    }
    case 'json_load': {
      return `${indent}auto j = nlohmann::json::parse(std::ifstream("${s.path || 'data.json'}"));`;
    }
    case 'json_save': {
      return `${indent}std::ofstream("${s.path || 'data.json'}") << nlohmann::json(${cppLiteral(s.value)}).dump();`;
    }
    case 'file_read': {
      return `${indent}std::ifstream in("${s.path || 'in.txt'}"); std::stringstream ss; ss << in.rdbuf(); auto ${s.name || 'data'} = ss.str();`;
    }
    case 'file_write': {
      return `${indent}std::ofstream("${s.path || 'out.txt'}") << ${cppLiteral(s.value)};`;
    }
    case 'log': {
      const lvl = s.level || 'info';
      return `${indent}spdlog::${lvl}(${cppLiteral(s.text || '')});`;
    }
    case 'sleep': {
      return `${indent}std::this_thread::sleep_for(std::chrono::milliseconds(${s.ms || 1000}));`;
    }
    case 'assert': {
      return `${indent}assert(${s.cond || 'true'});`;
    }
    case 'for': {
      return `${indent}for (auto& ${s.iter || 'x'} : ${s.source || '{}'}) { /* TODO */ }`;
    }
    case 'if': {
      return `${indent}if (${s.cond || 'true'}) { /* TODO */ }`;
    }
    case 'raw': {
      return `${indent}${s.code || ''}`;
    }
    default: {
      return `${indent}// unsupported stmt: ${s.kind}`;
    }
  }
}
