// codegen - walks IR and emits a single main.cpp
import { cppString, isIdent } from '../runtime/slug.mjs';

// type -> c++ type
const TYPE_MAP = {
  string: 'std::string',
  int: 'int',
  double: 'double',
  bool: 'bool',
  void: 'void',
  auto: 'auto',
  json: 'nlohmann::json',
  bytes: 'std::vector<uint8_t>',
  'vector<string>': 'std::vector<std::string>',
  'vector<int>': 'std::vector<int>',
  http_response: 'std::string',
  file: 'std::ifstream',
};

function cppType(t) { return TYPE_MAP[t] || 'std::string'; }

// zero literal for a return type when a fn body is empty
function cppZero(type) {
  switch (type) {
    case 'int': return '0';
    case 'double': return '0.0';
    case 'bool': return 'false';
    case 'string': return '""';
    case 'void': return '';
    case 'json': return 'nlohmann::json{}';
    case 'vector<string>': return 'std::vector<std::string>{}';
    case 'vector<int>': return 'std::vector<int>{}';
    default: return '""';
  }
}

// reject non-identifier names so a stray LLM value doesn't sneak in as c++
function ident(name, fallback) {
  return isIdent(name) ? name : (fallback || '_bad');
}

// emit a c++ literal from a JS value
function cppLiteral(v) {
  if (v === null || v === undefined) return '""';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : '0';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'string') return cppString(v);
  return cppString(String(v));
}

// cppExpr: like cppLiteral but for expression-like tokens (var name, math, init list {1,2,3})
// strict grammar - prompt-injection guard
const EXPR_RE = /^-{0,2}["{]?[A-Za-z_0-9][A-Za-z0-9_ .(),+\-*/%<>=!&|^~?{}\[\]'"`]*$/;
function cppExpr(v) {
  if (v === null || v === undefined) return '""';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : '0';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (typeof v === 'string') {
    const t = v.trim();
    // reject ; # ` and // - that's how injection gets in
    if (/[;#]/.test(t) || /`/.test(t) || /\/\//.test(t)) return '""';
    if (!EXPR_RE.test(t)) return '""';
    return v;
  }
  return cppString(String(v));
}

// rhsFor: if parser said this was a quoted string, always quote it. else use cppRhs.
function rhsFor(value, isString, knownIdents) {
  if (isString) return cppString(value ?? '');
  return cppRhs(value, knownIdents);
}

function cppRhs(v, knownIdents) {
  if (v === null || v === undefined) return '""';
  if (typeof v === 'number' || typeof v === 'boolean') return cppExpr(v);
  if (typeof v === 'string') {
    // bare word: known ident -> c++ var, else -> string literal
    if (/^[A-Za-z_]\w*$/.test(v)) {
      if (knownIdents && knownIdents.has(v)) return v;
      return cppString(v);
    }
    // multi-token: no operator -> string. operator -> c++ expression (with EXPR_RE guard)
    // narrow operator list: no `,` or `!` so "Hello, world!" doesn't sneak through
    const t = v.trim();
    const hasOp = /[+\-*\/=<>&|^%()[\]{}]/.test(t);
    if (!hasOp) return cppString(v);
    if (/^'/.test(t)) return cppString(v); // single quote is a char literal in c++
    if (/[;#`]/.test(t) || /\/\//.test(t) || !EXPR_RE.test(t)) return cppString(v);
    return v;
  }
  return cppString(String(v));
}

export function emitCpp(ir) {
  const out = [];
  out.push(`// generated by nlpc - do not edit`);
  out.push(`#include <iostream>`);
  out.push(`#include <string>`);
  out.push(`#include <vector>`);
  out.push(`#include <sstream>`);
  // unconditional headers. the emitter may reference these without any
  // matching requirement (json_load/json_save, sleep, assert, port env),
  // and trusting a transitive include from somewhere else is the bug
  // that broke file I/O in plain console apps.
  out.push(`#include <fstream>`);
  out.push(`#include <cassert>`);
  out.push(`#include <thread>`);
  out.push(`#include <chrono>`);
  out.push(`#include <cstdlib>`);
  out.push(`#include <filesystem>`);
  // emit std::regex(...) for route paths with `:param` capture groups,
  // so explicitly include <regex>. cpp-httplib transitively pulls it
  // in, but best practice is to include any std header you reference
  // directly in your own source.
  out.push(`#include <regex>`);
  // bug: for-each over a bare-word/string source emits std::string_view(...).
  // libstdc++ on linux tends to drag it in via <string>, but libc++/msvc
  // are stricter - include it ourselves so we don't depend on transitive
  // includes from somewhere we don't control.
  out.push(`#include <string_view>`);
  // optional headers (requirement-gated)
  const reqs = (ir.requirements || []).map(r => r.name.toLowerCase());
  if (reqs.some(r => /nlohmann|json/.test(r))) out.push(`#include <nlohmann/json.hpp>`);
  if (reqs.some(r => /httplib|cpr|cpp-httplib/.test(r))) out.push(`#include <httplib.h>`);
  if (reqs.some(r => /spdlog/.test(r))) out.push(`#include <spdlog/spdlog.h>`);
  if (reqs.some(r => /fmt/.test(r))) out.push(`#include <fmt/core.h>`);
  out.push('');
  // declarations (functions)
  for (const d of ir.declarations || []) {
    if (d.kind === 'function') {
      const params = (d.params || []).map(p => `${cppType(p.type)} ${ident(p.name, 'arg')}`).join(', ');
      const rettype = cppType(d.returns || 'void');
      out.push(`${rettype} ${ident(d.name, 'fn')}(${params}) {`);
      // knownIdents: param names are in scope as c++ identifiers, so
      // `return x` in a function `foo(int x)` should emit `return x;`
      // and not `return "x";`. this set is propagated to nested blocks
      // and grows as `set X = ...` introduces locals.
      const knownIdents = new Set((d.params || []).map(p => p.name));
      if (d.returns && d.returns !== 'void') {
        if (d.body && d.body.length) {
          const fnDeclared = new Set(knownIdents);
          for (const s of d.body) {
            const ln = emitStmt(s, '    ', { declared: fnDeclared, knownIdents });
            if (ln) out.push(ln);
          }
          // body didn't explicitly return; emit a typed zero so the c++
          // compiler doesn't reject the non-void function for missing
          // return path.
          out.push(`    return ${cppZero(d.returns)};`);
        } else {
          // offline mode never populates a body; emit a typed zero literal
          // so e.g. returns: 'int' compiles to `return 0;` not `return "";`.
          out.push(`    return ${cppZero(d.returns)};`);
        }
      }
      out.push(`}`);
      out.push('');
    } else if (d.kind === 'variable') {
      out.push(`${cppType(d.type || 'string')} ${ident(d.name, 'var')} = ${cppLiteral(d.value)};`);
    }
  }
  // main
  out.push(`int main() {`);
  out.push(`    std::ios::sync_with_stdio(false);`);
  out.push(`    std::cin.tie(nullptr);`);
  out.push('');
  // track names so the second `set x = ...` is a plain assignment
  const declared = new Set();
  const startBeh = (ir.behaviors || []).find(b => b.trigger === 'start');
  const routeBehs = (ir.behaviors || []).filter(b => b.trigger === 'route');
  if (routeBehs.length && reqs.some(r => /httplib|cpp-httplib/.test(r))) {
    out.push(`    httplib::Server svr;`);
    for (const r of routeBehs) {
      // cpp-httplib wants PascalCase methods
      const raw = String(r.method || 'GET').toLowerCase();
      const method = raw.charAt(0).toUpperCase() + raw.slice(1);
      // bug: cpp-httplib does NOT accept `:id` - use std::regex capture groups
      let path;
      {
        const p = r.path || '/';
        if (typeof p === 'string' && p.includes(':')) {
          const rx = p.replace(/:[^\/]+/g, '([^/]+)');
          path = `std::regex(R"(${rx})")`;
        } else {
          path = cppString(p);
        }
      }
      out.push(`    svr.${method}(${path}, [](const httplib::Request& req, httplib::Response& res) {`);
      // bug: don't emit "ok" fallback if the body already set the response
      let bodySetResponse = false;
      for (const s of r.body || []) {
        const ln = emitStmt(s, '        ', { routeCtx: true });
        if (ln) {
          if (s.kind === 'return') bodySetResponse = true;
          else if (s.kind === 'raw' && /\bres\.set_content\s*\(/.test(s.code || '')) bodySetResponse = true;
          else if (s.kind === 'call' && /res/.test(s.target || '')) bodySetResponse = true;
          out.push(ln);
        }
      }
      if (!bodySetResponse) out.push(`        res.set_content("ok", "text/plain");`);
      out.push(`    });`);
    }
    // PORT env var for PaaS hosts
    out.push(`    const char* nlpc_port = std::getenv("PORT");`);
    out.push(`    int port = nlpc_port ? std::atoi(nlpc_port) : 8080;`);
    out.push(`    svr.listen("0.0.0.0", port);`);
  } else if (startBeh) {
    // bug: top-level if/for become their own start-trigger behaviors. merge so we don't drop the rest
    const startBehs = (ir.behaviors || []).filter(b => b.trigger === 'start');
    // bug: `serve on port N` without routes still needs `httplib::Server svr;` declared
    let needsSvr = false;
    for (const sb of startBehs) for (const s of (sb.body || [])) if (s && s.kind === 'http_serve') needsSvr = true;
    if (needsSvr) out.push(`    httplib::Server svr;`);
    for (const sb of startBehs) {
      for (const s of sb.body || []) {
        const ln = emitStmt(s, '    ', { declared });
        if (ln) out.push(ln);
      }
    }
  }
  out.push(`    return 0;`);
  out.push(`}`);
  return out.join('\n');
}

function emitStmt(s, indent, ctx = {}) {
  if (!s || !s.kind) return null;
  const declared = ctx.declared || (ctx.declared = new Set());
  const knownIdents = ctx.knownIdents || declared;
  switch (s.kind) {
    case 'print': {
      return `${indent}std::cout << ${rhsFor(s.text, s.isString, knownIdents)} << std::endl;`;
    }
    case 'ask': {
      const name = ident(s.name, 'input');
      // bug: needed in knownIdents so a later `print name` resolves to the var
      if (s.name && /^[A-Za-z_]\w*$/.test(s.name)) {
        knownIdents.add(s.name);
        declared.add(s.name);
      }
      return [
        `${indent}std::cout << ${cppString(s.text || '> ')} << std::flush;`,
        `${indent}std::string ${name};`,
        `${indent}std::getline(std::cin, ${name});`,
      ].join('\n');
    }
    case 'set': {
      const v = ident(s.name, 'var');
      const rhs = rhsFor(s.value, s.isString, knownIdents);
      if (declared.has(v)) return `${indent}${v} = ${rhs};`;
      declared.add(v);
      knownIdents.add(v);
      // bug: `auto` on a string literal deduces `const char*` and breaks concat
      const isStringLit = s.isString && typeof s.value === 'string';
      const decl = isStringLit ? 'std::string' : 'auto';
      return `${indent}${decl} ${v} = ${rhs};`;
    }
    case 'call': {
      const target = ident(s.target, '_');
      // bug: drop empty-string args so a stray `()` doesn't pass `""` through
      const args = (s.args || []).filter(a => a && a.value !== '' && a.value !== null && a.value !== undefined).map(a => rhsFor(a.value, a.isString, knownIdents)).join(', ');
      return `${indent}${target}(${args});`;
    }
    case 'return': {
      // bug: inside a route the lambda is void -> res.set_content + return;
      const val = rhsFor(s.value, s.isString, knownIdents);
      if (ctx.routeCtx) {
        return `${indent}res.set_content(${val}, "text/plain");\n${indent}return;`;
      }
      return `${indent}return ${val};`;
    }
    case 'http_get': {
      // dispatch on s.method - default was always Get() which broke POST/PUT/DELETE
      const path = cppString(s.path || '');
      const verb = String(s.method || 'GET').toLowerCase();
      const cliMethod = ({ get: 'Get', post: 'Post', put: 'Put', delete: 'Delete', patch: 'Patch' })[verb] || 'Get';
      return [
        `${indent}auto cli = httplib::Client("http://localhost", 8080);`,
        `${indent}auto res = cli.${cliMethod}(${path});`,
        `${indent}if (res) std::cout << res->body << std::endl;`,
      ].join('\n');
    }
    case 'http_post':
    case 'http_put':
    case 'http_delete':
    case 'http_patch': {
      const path = cppString(s.path || '');
      const verb = String(s.method || 'POST').toLowerCase();
      const cliMethod = ({ post: 'Post', put: 'Put', delete: 'Delete', patch: 'Patch' })[verb] || 'Post';
      return [
        `${indent}auto cli = httplib::Client("http://localhost", 8080);`,
        `${indent}auto res = cli.${cliMethod}(${path}, std::string());`,
        `${indent}if (res) std::cout << res->body << std::endl;`,
      ].join('\n');
    }
    case 'http_serve': {
      // bug: port came in as a string "9090" and isIdent dropped it
      const raw = String(s.port ?? '');
      let port;
      if (/^\d+$/.test(raw)) port = raw;
      else if (isIdent(raw)) port = raw;
      else port = '8080';
      return `${indent}svr.listen("0.0.0.0", ${port});`;
    }
    case 'http_route': {
      // bug: was lowercase svr.get, which doesn't exist
      const raw = String(s.method || 'GET').toLowerCase();
      const method = raw.charAt(0).toUpperCase() + raw.slice(1);
      const path = cppString(s.path || '/');
      return `${indent}svr.${method}(${path}, [](const auto& req, auto& res) { res.set_content("ok", "text/plain"); });`;
    }
    case 'json_load': {
      // bug: hardcoded cppString opened a file literally named the bare word
      const filePath = rhsFor(s.path, s.isString, knownIdents);
      return `${indent}auto j = nlohmann::json::parse(std::ifstream(${filePath}));`;
    }
    case 'json_save': {
      // bug: same - path was hardcoded cppString
      const filePath = rhsFor(s.path, s.isString, knownIdents);
      const val = (s.valueIsString === false)
        ? rhsFor(s.value, false, knownIdents)
        : cppLiteral(s.value);
      return `${indent}{ std::ofstream _nlpc_out(${filePath}); _nlpc_out << nlohmann::json(${val}).dump(); }`;
    }
    case 'file_read': {
      // bug: same - path was hardcoded cppString
      const name = ident(s.name, 'data');
      const filePath = rhsFor(s.path, s.isString, knownIdents);
      return `${indent}{ std::ifstream _nlpc_in(${filePath}); std::stringstream _nlpc_ss; _nlpc_ss << _nlpc_in.rdbuf(); auto ${name} = _nlpc_ss.str(); }`;
    }
    case 'file_write': {
      // bug: same - path was hardcoded cppString
      const val = (s.valueIsString === false)
        ? rhsFor(s.value, false, knownIdents)
        : cppLiteral(s.value);
      const filePath = rhsFor(s.path, s.isString, knownIdents);
      return `${indent}{ std::ofstream _nlpc_out(${filePath}); _nlpc_out << ${val}; }`;
    }
    case 'file_rename': {
      // file-rename -> std::filesystem::rename
      const from = s.fromIsString === false ? rhsFor(s.from, false, knownIdents) : cppString(s.from ?? '');
      const to = s.toIsString === false ? rhsFor(s.to, false, knownIdents) : cppString(s.to ?? '');
      return `${indent}std::filesystem::rename(${from}, ${to});`;
    }
    case 'file_delete': {
      // file-delete -> std::filesystem::remove (path via rhsFor so bare-word paths work)
      const path = s.isString === false ? rhsFor(s.path, false, knownIdents) : cppString(s.path ?? '');
      return `${indent}std::filesystem::remove(${path});`;
    }
    case 'log': {
      const lvl = isIdent(s.level) ? s.level : 'info';
      // bug: spdlog::info() needs a Require: spdlog. std::clog is always available.
      return `${indent}std::clog << "[" << "${lvl}" << "] " << ${cppString(s.text ?? '')} << std::endl;`;
    }
    case 'sleep': {
      const ms = Number.isFinite(s.ms) ? s.ms : 1000;
      return `${indent}std::this_thread::sleep_for(std::chrono::milliseconds(${ms}));`;
    }
    case 'assert': {
      // reject anything outside a c++ expression grammar (prompt-injection guard)
      const cond = String(s.cond || 'true');
      if (!/^[A-Za-z0-9_ ().!=<>&|+\-*/'"?:]+$/.test(cond)) return `${indent}// unsafe assert cond dropped`;
      return `${indent}assert(${cond});`;
    }
    case 'for': {
      const iter = ident(s.iter, 'x');
      const inner = indent + '    ';
      // iter is in scope inside the body
      const childKnown = new Set(knownIdents);
      childKnown.add(iter);
      // bug: rhsFor (not cppExpr) so `for each x in items` uses `items` as the vector
      let src = rhsFor(s.source, s.isString, knownIdents);
      // bug: `[1,2,3]` isn't c++ but `{1,2,3}` is
      if (typeof s.source === 'string') {
        const t = s.source.trim();
        if (/^\[.*\]$/.test(t)) src = '{' + t.slice(1, -1) + '}';
      }
      // bug: `for each x in 5` - int has no begin/end, fake a list of N zeros
      if (typeof s.source === 'number' && Number.isFinite(s.source)) {
        src = `{${Array.from({ length: s.source }, () => '0').join(',')}}`;
      }
      // bug: `for each c in hello` iterates a const char* in c++20 - wrap in string_view
      const isBareWord = typeof s.source === 'string'
        && /^[A-Za-z_]\w*$/.test(s.source)
        && !(knownIdents && knownIdents.has(s.source));
      if ((s.isString && typeof s.source === 'string') || isBareWord) {
        src = `std::string_view(${src})`;
      }
      // bug: auto& can't bind to a temporary - auto&& does
      // bug: clone declared so a `set temp = ...` inside the loop body
      // doesn't bleed into the parent function's declared set; otherwise
      // a second loop with the same local would skip the `auto` and
      // emit a bare assignment into a scope that never declared it.
      const childDeclared = new Set(declared);
      const lines = [`${indent}for (auto&& ${iter} : ${src}) {`];
      for (const sub of s.body || []) {
        const ln = emitStmt(sub, inner, { declared: childDeclared, knownIdents: childKnown });
        if (ln) lines.push(ln);
      }
      lines.push(`${indent}}`);
      return lines.join('\n');
    }
    case 'if': {
      const cond = String(s.cond || 'true');
      // reject anything outside a c++ expression grammar (prompt-injection guard)
      if (!/^[A-Za-z0-9_ ().!=<>&|+\-*/'"?:.]+$/.test(cond)) return `${indent}// unsafe if cond dropped`;
      const inner = indent + '    ';
      // bug: same scope-clone rationale as `for` - locals from the if
      // body must not promote into the parent function's declared set
      const childDeclared = new Set(declared);
      const lines = [`${indent}if (${cond}) {`];
      for (const sub of s.body || []) {
        const ln = emitStmt(sub, inner, { declared: childDeclared, knownIdents });
        if (ln) lines.push(ln);
      }
      lines.push(`${indent}}`);
      return lines.join('\n');
    }
    case 'raw': {
      // raw is the explicit escape hatch per docs/language-spec.md
      const code = String(s.code || '');
      const trimmed = code.replace(/;\s*$/, '');
      return `${indent}${trimmed};`;
    }
    case 'unsupported': {
      // dropped (not raw) - the prose path is the prompt-injection vector
      return `${indent}// unsupported: ${s.text || ''}`;
    }
    default: {
      return `${indent}// unsupported stmt: ${s.kind}`;
    }
  }
}
